#!/usr/bin/env bash
export COUCHDB_IMAGE=${COUCHDB_IMAGE:="frodenas/couchdb"}
export COUCHDB_IMAGE_VERSION=${COUCHDB_IMAGE_VERSION:="1.6"}
export COUCHDB_ROOT=${COUCHDB_ROOT:="/var/lib/dokku/services/couchdb"}
export COUCHDB_BACKUP=${COUCHDB_DUMP:="https://raw.githubusercontent.com/danielebailo/couchdb-dump/master/couchdb-backup.sh"}

export PLUGIN_COMMAND_PREFIX="couchdb"
export PLUGIN_DATA_ROOT=$COUCHDB_ROOT
export PLUGIN_DATASTORE_PORTS=(5984)
export PLUGIN_DEFAULT_ALIAS="COUCHDB"
export PLUGIN_ALT_ALIAS="DOKKU_COUCHDB"
export PLUGIN_IMAGE=$COUCHDB_IMAGE
export PLUGIN_IMAGE_VERSION=$COUCHDB_IMAGE_VERSION
export PLUGIN_SCHEME="http"
export PLUGIN_SERVICE="CouchDB"
export PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi

if [[ -d "$PLUGIN_DATA_ROOT/*" ]]; then
  rm -rf "${PLUGIN_DATA_ROOT:?}/*"
fi
